## Data Science

- A filed of science that study thd data, analyse the data and performs various steps on the data to get valuable insights
- ex: goolge, goolge maps, amazon , uber, tickets etc
- It has some powerful libraries or packages
    - Numpy, Pandas, Matplotlib etc
        - NumPy 
            - Scientific caluculation
        - Pandas
            - Data Manupulation, analysis and cleaning
        - Matplotlib
            - Visulization
    

## Numpy 

- It means Numerical Python
- It is one of packages in Data Science
- Here we dealing with array kind data
- The main purpose of this pakcage is to do scientific caluculations
    - Logarithmic, Linear alzebra, FT, Tri, exp 
- smaller memory consumption
- better runtime


In [1]:
import numpy

In [ ]:
## installation
-- pip install numpy


In [5]:
a = numpy.array([3,5,7])
print(a)
a
type(a)

[3 5 7]


numpy.ndarray

In [3]:
import numpy as np

In [7]:
a = np.array([2,6,5,4,3])
a

array([2, 6, 5, 4, 3])

In [8]:
b = np.array([[3,4,5],[7,6,5],[8,7,5]])
b

array([[3, 4, 5],
       [7, 6, 5],
       [8, 7, 5]])

In [23]:
### predefined functions

print(type(b))
print(b.dtype)
print(b.ndim)
print(a.ndim)
print(a.shape)
print(b.shape)
print(b.size)
np.__version__


<class 'numpy.ndarray'>
int32
2
1
(5,)
(3, 3)
9


'1.18.5'

In [22]:
d = np.array([[[1,2,3],[5,8,5]]])
d.ndim


3

### range()

In [27]:
ar = np.array(range(5))
print(ar)
ar1 = np.array(range(1,10))
print(ar1)
ar2 = np.array(range(1,20,3))
print(ar2)

[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[ 1  4  7 10 13 16 19]


## arange()

In [30]:
x = np.arange(9)
print(x)
y = np.arange(1,10)
print(y)
z = np.arange(1,40,5)
print(z)

[0 1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]
[ 1  6 11 16 21 26 31 36]


## reshape()

In [31]:
a1 = np.arange(25).reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
b1 = np.arange(12).reshape(-1,4)
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
b1 = np.arange(12).reshape(2,-2)
b1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [40]:
o = np.ones((7,4),dtype = int)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
z = np.zeros((3,5),dtype = int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
s = np.full((4,4),7)
s


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [49]:
e = np.eye(6)
e

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [42]:
n = np.arange(9).reshape(3,3)
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
d = np.diag(n)

In [44]:
d

array([0, 4, 8])

In [45]:
d.sum()

12