## Conti... NumPy

In [1]:
import numpy as np

In [3]:
## returns  equally spaced numbers within range

a = np.linspace(1,10,4)
a

array([ 1.,  4.,  7., 10.])

## random()

In [14]:
r = np.random.randint(10)
print(r)
r1 = np.random.randint(5,10)
print(r1)
r2 = np.random.randint(1,10,3)
print(r2)
r3 = np.random.randint(10,100,(2,4))
print(r3)
r4 = np.random.randint(10,50,12).reshape(3,4)
print(r4)

8
8
[5 6 2]
[[86 23 60 28]
 [81 13 39 84]]
[[42 33 46 27]
 [18 11 31 43]
 [39 25 49 30]]


In [16]:
n = np.random.random(3)
n

array([0.28863101, 0.68402128, 0.7135528 ])

In [17]:
n1 = np.random.randn(4)

In [18]:
n1

array([-1.46765591,  0.17785175, -0.00733861, -0.6729829 ])

In [19]:
## Slicing

r = np.random.randint(10,100,(4,4))
r

array([[98, 17, 99, 72],
       [10, 96, 91, 21],
       [20, 42, 66, 79],
       [98, 99, 92, 64]])

In [20]:
r[0]

array([98, 17, 99, 72])

In [21]:
r[0:2]

array([[98, 17, 99, 72],
       [10, 96, 91, 21]])

In [22]:
r[2:]

array([[20, 42, 66, 79],
       [98, 99, 92, 64]])

In [23]:
r

array([[98, 17, 99, 72],
       [10, 96, 91, 21],
       [20, 42, 66, 79],
       [98, 99, 92, 64]])

In [24]:
r[0:2,0:2]

array([[98, 17],
       [10, 96]])

In [25]:
r[:]

array([[98, 17, 99, 72],
       [10, 96, 91, 21],
       [20, 42, 66, 79],
       [98, 99, 92, 64]])

In [26]:
r[:4]

array([[98, 17, 99, 72],
       [10, 96, 91, 21],
       [20, 42, 66, 79],
       [98, 99, 92, 64]])

In [27]:
a = np.matrix('1,2;5,7')
a

matrix([[1, 2],
        [5, 7]])

In [28]:
b = np.matrix('7,8;9,2')
b

matrix([[7, 8],
        [9, 2]])

In [29]:
print(np.add(a,b))

[[ 8 10]
 [14  9]]


In [30]:
a1 = np.array([[1,2],[6,7]])
a2 = np.array([[6,3],[8,3]])


In [31]:
a1+a2

array([[ 7,  5],
       [14, 10]])

In [32]:
np.subtract(a,b)

matrix([[-6, -6],
        [-4,  5]])

In [33]:
np.matmul(a,b)

matrix([[25, 12],
        [98, 54]])

In [34]:
np.multiply(a,b)

matrix([[ 7, 16],
        [45, 14]])

In [35]:
a

matrix([[1, 2],
        [5, 7]])

In [36]:
a+4

matrix([[ 5,  6],
        [ 9, 11]])

In [37]:
a*5

matrix([[ 5, 10],
        [25, 35]])

In [38]:
a-2

matrix([[-1,  0],
        [ 3,  5]])

In [39]:
a

matrix([[1, 2],
        [5, 7]])

In [41]:
a>3

matrix([[False, False],
        [ True,  True]])

In [43]:
a[a>3].sum()

12

### Scientific computation

In [44]:
m = np.arange(16).reshape(8,2)
m

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [45]:
print(np.mean(m))

7.5


In [46]:
print(np.std(m))

4.6097722286464435


In [47]:
print(np.median(m))

7.5


In [48]:
print(np.dot(a,b))

[[25 12]
 [98 54]]


In [49]:
np.log(0)

<ipython-input-49-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [50]:
np.log(1)

0.0

In [51]:
np.log([1,6,4,3])


array([0.        , 1.79175947, 1.38629436, 1.09861229])

In [52]:
np.exp(1)

2.718281828459045

In [53]:
np.exp(6)

403.4287934927351

In [54]:
np.exp([4,7,6])

array([  54.59815003, 1096.63315843,  403.42879349])

In [55]:
print(dir(np),end=' ')

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [56]:
np.sin(0)

0.0

In [57]:
np.cos(0)

1.0

In [58]:
np.tan(0)

0.0

## Pandas

- Means PanelData
- one of the data science package
- Used for data manipulation, analysis and cleaning
- It contains two data structures
    - 1. Series
    - 2. DataFrames
- Sequence of data
- A data frame is data with rows and columns


In [ ]:
## installation
-- pip install pandas

In [60]:
import pandas as pd

In [61]:
pd.__version__

'1.0.5'

In [62]:
st = 'hello'
pd.Series(st)

0    hello
dtype: object

In [63]:
s1 = 'Good evening all'.split()
pd.Series(s1)

0       Good
1    evening
2        all
dtype: object

In [66]:
l = [123,'hi',5.4]
pd.Series(l, index = ['int','str','float'])

int      123
str       hi
float    5.4
dtype: object

In [67]:
t = ('a','e','i','o','u')
pd.Series(t, index = ['v1','v2','v3','v4','v5'])

v1    a
v2    e
v3    i
v4    o
v5    u
dtype: object

In [68]:
dic = {'k1':145,'k2':'daf','k3':8.5}
pd.Series(dic)

k1    145
k2    daf
k3    8.5
dtype: object

In [69]:
s = 'hello all welcome to python session'.split()
pd.DataFrame(s)

0
0    hello
1      all
2  welcome
3       to
4   python
5  session

In [70]:
l = [1,'dafa',56,34,9.4]
pd.DataFrame(l)

0
0     1
1  dafa
2    56
3    34
4   9.4

In [71]:
t = (1,4,5,'asdf')
pd.DataFrame(t, index = [1,2,3,4])

0
1     1
2     4
3     5
4  asdf

In [72]:
dic = {'k1':145,'k2':'daf','k3':8.5}
pd.DataFrame(dic, index = (1,2,3))

k1   k2   k3
1  145  daf  8.5
2  145  daf  8.5
3  145  daf  8.5